name: Build and Deploy Laravel (Production - EVA)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Windows runner

    defaults:
      run:
        shell: '"C:\Program Files\PowerShell\7\pwsh.exe" -command {0}'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
          ini-file: production

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Run Laravel Migrations
        run: php artisan migrate --force

      - name: Deploy to IIS Folder
        run: |
          Remove-Item -Recurse -Force "C:\inetpub\wwwroot\EVA" -ErrorAction SilentlyContinue
          Copy-Item -Recurse -Force . "C:\inetpub\wwwroot\EVA"
