name: Build and Deploy Laravel App (Production - EVA)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Windows runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Copy Files to Deployment Folder
        run: |
          if (Test-Path "C:\Naturebackend") {
            Remove-Item -Recurse -Force "C:\Naturebackend\*" -ErrorAction SilentlyContinue
          }
          Copy-Item -Recurse -Force . "C:\Naturebackend"

      - name: Set Permissions (Storage & Bootstrap Cache)
        run: |
          icacls "C:\Naturebackend\storage" /grant "Users:(OI)(CI)F"
          icacls "C:\Naturebackend\bootstrap\cache" /grant "Users:(OI)(CI)F"

      - name: Run Laravel Optimizations
        run: |
          cd C:\Naturebackend
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
