name: Deploy Laravel to C:\natureBackend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    name: Build & Deploy Laravel

    steps:
      # 1. Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup PHP with needed extensions
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer
          ini-file: production
          extensions: fileinfo, mbstring, intl, pdo_mysql

      # 3. Install dependencies
      - name: Install PHP Dependencies
        run: composer install --no-dev --optimize-autoloader --no-scripts

      # 4. Cache Laravel bootstrap/cache & vendor for faster builds
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # 5. Prepare target folder
      - name: Prepare Deploy Folder
        shell: pwsh
        run: |
          $target = "C:\natureBackend"

          if (Test-Path $target) {
            Write-Output "Cleaning $target..."
            Remove-Item -Recurse -Force $target
          }
          New-Item -ItemType Directory -Path $target | Out-Null
          icacls $target /grant "Network Service:(OI)(CI)F" /T
          icacls $target /grant "$env:USERNAME:(OI)(CI)F" /T

      # 6. Copy files to target
      - name: Deploy Project to C:\natureBackend
        shell: pwsh
        run: |
          $source = "${{ github.workspace }}"
          $target = "C:\natureBackend"

          Write-Output "Source: $source"
          Write-Output "Target: $target"

          Copy-Item -Path "$source\*" -Destination $target -Recurse -Force
          Write-Output "✅ Deployment completed."

          Write-Output "📂 Files in $target:"
          Get-ChildItem $target

      # 7. (Optional) Laravel post-deploy commands
      - name: Run Laravel Post-Deploy Commands
        shell: pwsh
        run: |
          cd C:\natureBackend
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan view:clear
          php artisan config:cache
