name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer
          ini-file: production
          extensions: fileinfo, mbstring, intl, pdo_mysql

      - name: Check PHP & Composer versions
        run: |
          php -v
          php -m
          composer -V

      - name: Fix Composer global config
        run: composer global config --unset bin-dir

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader --no-scripts

      - name: Publish project to C:\natureBackend
        run: |
          $target = "C:\natureBackend"
          if (Test-Path $target) {
            Remove-Item -Recurse -Force $target
          }
          New-Item -ItemType Directory -Path $target | Out-Null
          Copy-Item -Path .\* -Destination $target -Recurse -Force
          Write-Output "Project published to $target"

      - name: Laravel cache optimizations
        run: |
          cd C:\natureBackend
          php artisan config:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
