name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer
          ini-file: production
          extensions: fileinfo, mbstring, intl, pdo_mysql

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader --no-scripts

      - name: Publish project to C:\natureBackend
        shell: pwsh
        run: |
          $source = "${{ github.workspace }}"
          $target = "C:\natureBackend"

          Write-Output "Source: $source"
          Write-Output "Target: $target"

          if (Test-Path $target) {
            Remove-Item -Recurse -Force $target
          }
          New-Item -ItemType Directory -Path $target | Out-Null

          Copy-Item -Path "$source\*" -Destination $target -Recurse -Force

          Write-Output "Project published to $target"
          Get-ChildItem $target
