name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer
          ini-file: production

      - name: Check PHP & Composer versions
        run: |
          php -v
          composer -V

      - name: Fix Composer global config (bad bin-dir)
        run: composer global config --unset bin-dir

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader --no-scripts

      - name: Laravel cache optimizations
        run: |
          php artisan config:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
