name: Build and Deploy Laravel App (Production - EVA)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Your Windows runner

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer
          ini-file: production

      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Copy Environment File
        run: Copy-Item .env.production .env -Force

      - name: Run Laravel Optimizations
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan route:cache
          php artisan config:cache
          php artisan view:cache

      - name: Deploy to IIS Folder
        run: |
          Remove-Item -Recurse -Force "C:\EVAWebsite\*" -ErrorAction SilentlyContinue
          Copy-Item -Recurse -Force . "C:\EVAWebsite"
