name: Build and Deploy Laravel App (Production - EVA)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Windows runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      

      - name: Copy Files to Deployment Folder
        run: |
          if exist C:\Naturebackend (
            rmdir /s /q C:\Naturebackend
          )
          xcopy . C:\Naturebackend /E /H /C /I /Y
        shell: cmd

      - name: Set Permissions (Storage & Bootstrap Cache)
        run: |
          icacls "C:\Naturebackend\storage" /grant "Users:(OI)(CI)F"
          icacls "C:\Naturebackend\bootstrap\cache" /grant "Users:(OI)(CI)F"
        shell: cmd

      - name: Run Laravel Optimizations
        run: |
          cd C:\Naturebackend
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
        shell: cmd
